In [1]:
#pip install python-chess

#import for file loading
import os
#import chess game from python-chess
import chess
#import chess.pgn for reading and splicing .pgn game files
import chess.pgn
#import chess_value_network to divide a chessboard into channels representing states and values
from chess_value_network import chess_value_network
#chess_data_load loads and formats data from .pgn folder
from Chess_Data_load import Chess_Data_Load
#tensorChess is the CNN model; input: a chess board state, output: a scalar val
from tensorChess import tensorChess
#import tensorflow machine learning functions
import tensorflow as tf
import numpy
import pandas as pd
#import a simple move evaluator to take a board, run it through CNN and get return a scalar
from move_eval import move_eval

In [3]:
#load chess board
board = chess.Board()

In [4]:
#here is a list of all legal moves from the current start state 
#(this is for whoever's turn it is)
board.legal_moves

<LegalMoveGenerator at 0x62e2df410 (Nh3, Nf3, Nc3, Na3, h3, g3, f3, e3, d3, c3, b3, a3, h4, g4, f4, e4, d4, c4, b4, a4)>

In [5]:
#print current board state, at game start the board is the chess board start state
print(board)

r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R


In [6]:
#load our chess value network to see how the initial board state gets represented
#the board is represented as a 5 x 8 x 8 vector.  5 "state" channels used in a 8x8 board
states = chess_value_network(board)
#here is what the CNN will recieve
print(states.process())

[[[0 1 1 1 1]
  [0 0 1 0 1]
  [0 0 1 1 1]
  [0 1 0 1 1]
  [0 1 1 0 1]
  [0 0 1 1 1]
  [0 0 1 0 1]
  [0 1 1 1 1]]

 [[0 0 0 1 1]
  [0 0 0 1 1]
  [0 0 0 1 1]
  [0 0 0 1 1]
  [0 0 0 1 1]
  [0 0 0 1 1]
  [0 0 0 1 1]
  [0 0 0 1 1]]

 [[0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]]

 [[0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]]

 [[0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]]

 [[0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]]

 [[1 0 0 1 1]
  [1 0 0 1 1]
  [1 0 0 1 1]
  [1 0 0 1 1]
  [1 0 0 1 1]
  [1 0 0 1 1]
  [1 0 0 1 1]
  [1 0 0 1 1]]

 [[1 1 1 1 1]
  [1 0 1 0 1]
  [1 0 1 1 1]
  [1 1 0 1 1]
  [1 1 1 0 1]
  [1 0 1 1 1]
  [1 0 1 0 1]
  [1 1 1 1 1]]]


In [7]:
#loading and printing our first full game in the dataset. 
#This game has 91 moves and ends in a draw

for fn in os.listdir("KingBase2019-pgn"):
    pgn = open(os.path.join("KingBase2019-pgn", fn))
    game = chess.pgn.read_game(pgn)
    result = game.headers['Result']
    board = game.board()
    move_count = 0
    for move in game.mainline_moves():
        move_count += 1
        print(move_count)
        print(board)
        board.push(move)
    print(result)
    break

1
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R
2
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . P . . . . .
. . . . . . . .
P P . P P P P P
R N B Q K B N R
3
r n b q k b n r
p p p p . p p p
. . . . . . . .
. . . . p . . .
. . P . . . . .
. . . . . . . .
P P . P P P P P
R N B Q K B N R
4
r n b q k b n r
p p p p . p p p
. . . . . . . .
. . . . p . . .
. . P . . . . .
. . N . . . . .
P P . P P P P P
R . B Q K B N R
5
r . b q k b n r
p p p p . p p p
. . n . . . . .
. . . . p . . .
. . P . . . . .
. . N . . . . .
P P . P P P P P
R . B Q K B N R
6
r . b q k b n r
p p p p . p p p
. . n . . . . .
. . . . p . . .
. . P . . . . .
. . N . P . . .
P P . P . P P P
R . B Q K B N R
7
r . b q k b . r
p p p p . p p p
. . n . . n . .
. . . . p . . .
. . P . . . . .
. . N . P . . .
P P . P . P P P
R . B Q K B N R
8
r . b q k b . r
p p p p . p p p
. . n . . n . .
. . . . p . . .
. . P . . . . .
P . N . 

In [8]:
#here is the same data represented by our chess_value_network

for fn in os.listdir("KingBase2019-pgn"):
    pgn = open(os.path.join("KingBase2019-pgn", fn))
    game = chess.pgn.read_game(pgn)
    board = game.board()
    move_count = 0
    for move in game.mainline_moves():
        move_count += 1
        print(move_count)
        board.push(move)
        state = chess_value_network(board)
        print(state.process())
    print(result)
    break

1
[[[0 1 1 1 0]
  [0 0 1 0 0]
  [0 0 1 1 0]
  [0 1 0 1 0]
  [0 1 1 0 0]
  [0 0 1 1 0]
  [0 0 1 0 0]
  [0 1 1 1 0]]

 [[0 0 0 1 0]
  [0 0 0 1 0]
  [0 0 0 0 0]
  [0 0 0 1 0]
  [0 0 0 1 0]
  [0 0 0 1 0]
  [0 0 0 1 0]
  [0 0 0 1 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [1 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 1 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[1 0 0 1 0]
  [1 0 0 1 0]
  [1 0 0 1 0]
  [1 0 0 1 0]
  [1 0 0 1 0]
  [1 0 0 1 0]
  [1 0 0 1 0]
  [1 0 0 1 0]]

 [[1 1 1 1 0]
  [1 0 1 0 0]
  [1 0 1 1 0]
  [1 1 0 1 0]
  [1 1 1 0 0]
  [1 0 1 1 0]
  [1 0 1 0 0]
  [1 1 1 1 0]]]
2
[[[0 1 1 1 1]
  [0 0 1 0 1]
  [0 0 1 1 1]
  [0 1 0 1 1]
  [0 1 1 0 1]
  [0 0 1 1 1]


In [9]:
#here we are going to load our full chess data set.
#this looks in our directory and finds the processed_data_test.npz that has already
#been processed for this demo
chess_dataset = Chess_Data_Load()

#if you would like to look at the data you can do so here:
#chess_dataset.show_x_y()

#we get our xtr and ytr sets
data_x = chess_dataset.get_x()
data_y = chess_dataset.get_y()

#we load our model
model = tensorChess()

#we are using the Adam optimization
#the reasoning behind choosing Adam that its not only easy but its computationally cheap
#because this process is being tested on my little laptop I chose to use the fastest 
#optim
optim = tf.keras.optimizers.Adam()

#compile the model we have built
#we are using a "mean_squared_error" loss which means the closer to 0 our training set is
#the better
model.compile(loss='mean_squared_error', batch_size=256, optimizer = optim)


#train your model!
model.fit(data_x, data_y)

#print the model summary so you can see the layers at work
model.summary()


(100036, 8, 8, 5) (100036,)
Train on 100036 samples
100036/100036 [==============================] - 23s 234us/sample - loss: 0.7061
Model: "tensor_chess"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              multiple                  736       
_________________________________________________________________
conv2d_1 (Conv2D)            multiple                  2320      
_________________________________________________________________
conv2d_2 (Conv2D)            multiple                  4640      
_________________________________________________________________
conv2d_3 (Conv2D)            multiple                  9248      
_________________________________________________________________
conv2d_4 (Conv2D)            multiple                  9248      
_________________________________________________________________
conv2d_5 (Conv2D)            multiple                

In [10]:
#we will save this model so it can be used by move_eval class
model.save("save_model/my_model")

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: save_model/my_model/assets


In [11]:
#lets play a game!
#here we have a simple leaf exploration function, where we take the list of all
#available moves from a current state, and check each of their "values" using the trained
#CNN.  This list of tuples (value, move) is then returned
def explore_leaves(s, v):
    x = []
    for e in s.edges():
        s.board.push(e)
        x.append((v(s), e))
        s.board.pop()
    return x

#a getkey function to just get the value for sorting
def getKey(item):
    return item[0]
    

In [12]:
#lets get our evaluator class up
evaluate = move_eval()
#lets get a new chess_value_network
my_states = chess_value_network()

#have the CNN play against itself!
while not my_states.board.is_game_over():
    moves = explore_leaves(my_states, evaluate)
    sorted(moves, key=getKey, reverse=my_states.board.turn)
    best_move = moves[0]
    print(best_move[1])
    my_states.board.push(best_move[1])

g1h3
g8h6
h3g5
h8g8
g5h7
g8h8
h7f8
h8g8
f8h7
g8h8
h7f8
h8g8
f8h7
g8h8
h7f8
h8g8
f8h7
g8h8
h7f8
h8g8
f8h7
g8h8
h7f8


In [ ]:
#it played a game! IT SUCKS AT PLAYING CHESS!
#To-Do:
#   -***Reduce loss value dramatically***
#   -Consider different repsentation of states in chess_value_network
#   -Train on larger dataset
#   -Allow for human input to play against CNN (or get CNN return move)